<table border="0">
  <tr>
    <td width="75%">
      <h1>仉启明</h1>
      <p><b>本科生</b></p>
      <p><b>浙江万里学院</b></p>
      <p><b>邮箱：zzzqm@outlook.com</b></p>
      <p><b>地址：宁波市鄞州区浙江万里学院</b></p>
    </td>
    <td width="25%">
      <img src="/zhengjianzhao.png" width="100%">      % 1606626563429.png
    </td>
  </tr>
</table>

theme: jekyll-theme-cayman